import { Geist, Geist_Mono } from "next/font/google";
import { ContentContextProvider } from "@/lib/context/ContentContext";
import Navbar from "@/app/_components/Navbar/page";
import { ToastContainer } from "react-toastify";
import Sidebar from "@/app/_components/Sidebar/page";
// import "./scss/main.scss";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function PreviewLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="stylesheet" href="https://codercrafter.in/assets/css/style.css" />
                <link rel="stylesheet" href="https://codercrafter.in/assets/css/uikit.css" />
                <link rel="stylesheet" href="https://codercrafter.in/assets/css/icons.css" />
                <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" />
                <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
                {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" /> */}

                {/* <script noModule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script> */}
                <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossOrigin="anonymous"></script>

            </head>
            <body className={`expand-menu`}>
                <ContentContextProvider>
                    <div id="wrapper" className="horizontal" >
                        <Navbar />
                        <div id="popupContainer" className="popup_container" >
                        </div>
                        <div
                            className="uk-sticky-placeholder"
                            style={{ height: 72, margin: 0 }}
                            bis_skin_checked={1}
                        />
                        {children}

                    </div>
                    <script src="https://code.jquery.com/jquery-3.6.0.min.js" crossOrigin="anonymous"></script>
                    <script src="/assets/js/uikit.js"></script>
                    <script src="/assets/js/tippy.all.min.js"></script>
                    <script src="/assets/js/simplebar.js"></script>
                    {/* <script src="/assets/js/custom.js"></script> */}
                    <script src="/assets/js/bootstrap-select.min.js"></script>
                    <script src="https://unpkg.com/ionicons@5.2.3/dist/ionicons.js"></script>
                </ContentContextProvider>
            </body>
        </html>
    );
}
