import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ContentContextProvider } from "@/lib/context/ContentContext";
import Navbar from "@/app/_components/Navbar/page";
import { ToastContainer } from "react-toastify";
import Sidebar from "@/app/_components/Sidebar/page";
// import "./scss/main.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="stylesheet" href="/assets/css/style.css" /> */}
        <link rel="stylesheet" href="/assets/css/icons.css" />
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
        <link rel="stylesheer" href="/assets/css/animate.css" />
        <link rel="stylesheet" href="/assets/css/dataTables.bootstrap4.min.css" />
        <link rel="stylesheet" href="/assets/css/fontawesome.min.css" />
        <link rel="stylesheet" href="/assets/css/all.min.css" />
        {/* <link rel="stylesheet" href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css" /> */}
        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script src="/assets/js/jquery-3.6.0.min.js" />
        <script src="/assets/js/feather.min.js" />
        <script src="/assets/js/jquery.slimscroll.min.js" />
        <script src="/assets/js/dataTables.bootstrap4.min.js" />
        <script src="/assets/js/bootstrap.bundle.min.js" />
        <script src="/assets/js/apexcharts.min.js" />
        <script src="/assets/chart-data.js" />
      </head>
      <body className={`expand-menu`}>
        <ContentContextProvider>
          <div id="main-wrapper" >
            <Navbar />
            <Sidebar />
            <ToastContainer />
            <div className="page-wrapper" >
              {children}
            </div>
          </div>
        </ContentContextProvider>
      </body>
    </html>
  );
}
